import type { ComponentType } from "react";
import {
  Add01Icon,
  AnchorPointIcon,
  Atom01Icon,
  BrainIcon,
  Bug02Icon,
  CafeIcon,
  CircleIcon,
  Clock01Icon,
  CloudIcon,
  Coffee01Icon,
  CoffeeBeansIcon,
  CodeIcon,
  CompassIcon,
  ComputerIcon,
  ComputerTerminal01Icon,
  CookieIcon,
  Crown02Icon,
  CubeIcon,
  Database01Icon,
  Diamond01Icon,
  Dna01Icon,
  Doctor01Icon,
  DollarCircleIcon,
  Download01Icon,
  DropletIcon,
  EarthIcon,
  FavouriteIcon,
  FileEditIcon,
  FireIcon,
  Flag01Icon,
  FlashIcon,
  FlowerIcon,
  Folder01Icon,
  Folder02Icon,
  Folder03Icon,
  GameIcon,
  GearsIcon,
  GithubIcon,
  Globe02Icon,
  HeadphonesIcon,
  HexagonIcon,
  HotAirBalloonIcon,
  House01Icon,
  Image01Icon,
  InboxIcon,
  Key01Icon,
  KidIcon,
  Knife01Icon,
  Lamp01Icon,
  LaptopIcon,
  Leaf01Icon,
  LibraryIcon,
  Link01Icon,
  Mail01Icon,
  MaskIcon,
  Megaphone01Icon,
  MicroscopeIcon,
  MixerIcon,
  MoonIcon,
  Mortarboard01Icon,
  MountainIcon,
  MoveIcon,
  Mp301Icon,
  MusicNote01Icon,
  Notebook01Icon,
  NoteIcon,
  OctagonIcon,
  Office365Icon,
  OvalIcon,
  PackageIcon,
  PaintBoardIcon,
  PaintBrush01Icon,
  PaintBucketIcon,
  PencilIcon,
  PenTool01Icon,
  PercentIcon,
  Pizza01Icon,
  Pulse01Icon,
  PuzzleIcon,
  Rocket01Icon,
  RssIcon,
  Scissor01Icon,
  Search01Icon,
  Shield01Icon,
  Shirt01Icon,
  ShoppingBasket01Icon,
  ShoppingCart01Icon,
  SkullIcon,
  SmileIcon,
  SnowIcon,
  StarIcon,
  SteakIcon,
  Stethoscope02Icon,
  StrategyIcon,
  Sun01Icon,
  Target01Icon,
  TaxiIcon,
  TeaIcon,
  TelephoneIcon,
  TestTube01Icon,
  ToolsIcon,
  Tornado01Icon,
  TractorIcon,
  TrafficLightIcon,
  Train01Icon,
  Tree01Icon,
  Triangle01Icon,
  TruckIcon,
  UmbrellaIcon,
  UniversityIcon,
  UsbIcon,
  UserIcon,
  VegetarianFoodIcon,
  VolleyballIcon,
  Wallet01Icon,
  WatermelonIcon,
  Wifi01Icon,
  WorkflowSquare01Icon,
  Wrench01Icon,
  Yoga01Icon,
  ZapIcon,
  ZoomIcon,
} from "hugeicons-react";

export interface PickerIcon {
  /** Stable identifier — stored on Project / Worktree as iconName. */
  name: string;
  /** Search keywords (lowercased). */
  label: string;
  Component: ComponentType<{ size?: number }>;
}

/**
 * Curated set for the icon picker dialog. Stable string keys so saved
 * state survives library version bumps; if a stored name isn't in the
 * registry, lookups fall back to the project's glyph cleanly via
 * `lookupPickerIcon`.
 */
export const PICKER_ICONS: PickerIcon[] = [
  { name: "Folder01", label: "folder", Component: Folder01Icon },
  { name: "Folder02", label: "folder file", Component: Folder02Icon },
  { name: "Folder03", label: "folder shared", Component: Folder03Icon },
  { name: "House01", label: "home house", Component: House01Icon },
  { name: "Library", label: "library books", Component: LibraryIcon },
  { name: "University", label: "university school college", Component: UniversityIcon },

  { name: "Note", label: "note paper text", Component: NoteIcon },
  { name: "Notebook01", label: "notebook journal", Component: Notebook01Icon },
  { name: "FileEdit", label: "file edit document", Component: FileEditIcon },
  { name: "Image01", label: "image picture photo", Component: Image01Icon },
  { name: "Mp301", label: "music audio mp3", Component: Mp301Icon },
  { name: "MusicNote01", label: "music note song", Component: MusicNote01Icon },
  { name: "Headphones", label: "headphones audio", Component: HeadphonesIcon },

  { name: "Code", label: "code programming source", Component: CodeIcon },
  { name: "ComputerTerminal01", label: "terminal shell command", Component: ComputerTerminal01Icon },
  { name: "Computer", label: "computer pc desktop", Component: ComputerIcon },
  { name: "Laptop", label: "laptop computer", Component: LaptopIcon },
  { name: "Database01", label: "database storage data", Component: Database01Icon },
  { name: "Cloud", label: "cloud storage", Component: CloudIcon },
  { name: "Cube", label: "cube package box", Component: CubeIcon },
  { name: "Package", label: "package delivery", Component: PackageIcon },
  { name: "Github", label: "github git repository", Component: GithubIcon },
  { name: "Office365", label: "office microsoft", Component: Office365Icon },
  { name: "Usb", label: "usb cable", Component: UsbIcon },
  { name: "Wifi01", label: "wifi internet wireless", Component: Wifi01Icon },

  { name: "Brain", label: "brain mind ai", Component: BrainIcon },
  { name: "Atom01", label: "atom science chemistry", Component: Atom01Icon },
  { name: "Dna01", label: "dna biology genetics", Component: Dna01Icon },
  { name: "TestTube01", label: "test tube experiment science", Component: TestTube01Icon },
  { name: "Microscope", label: "microscope research science", Component: MicroscopeIcon },
  { name: "Pulse01", label: "pulse health activity", Component: Pulse01Icon },
  { name: "Stethoscope02", label: "stethoscope medical health", Component: Stethoscope02Icon },
  { name: "Doctor01", label: "doctor medical hospital", Component: Doctor01Icon },

  { name: "Wallet01", label: "wallet cash money", Component: Wallet01Icon },
  { name: "ShoppingCart01", label: "shopping cart store", Component: ShoppingCart01Icon },
  { name: "ShoppingBasket01", label: "shopping basket store", Component: ShoppingBasket01Icon },
  { name: "DollarCircle", label: "dollar money currency", Component: DollarCircleIcon },
  { name: "Percent", label: "percent percentage", Component: PercentIcon },
  { name: "Crown02", label: "crown royalty premium", Component: Crown02Icon },
  { name: "Diamond01", label: "diamond gem premium", Component: Diamond01Icon },

  { name: "Pizza01", label: "pizza food", Component: Pizza01Icon },
  { name: "Coffee01", label: "coffee cup drink", Component: Coffee01Icon },
  { name: "CoffeeBeans", label: "coffee beans", Component: CoffeeBeansIcon },
  { name: "Tea", label: "tea drink", Component: TeaIcon },
  { name: "Cafe", label: "cafe coffee", Component: CafeIcon },
  { name: "Cookie", label: "cookie food", Component: CookieIcon },
  { name: "Steak", label: "steak meat food", Component: SteakIcon },
  { name: "Knife01", label: "knife kitchen", Component: Knife01Icon },
  { name: "Watermelon", label: "watermelon fruit", Component: WatermelonIcon },
  { name: "VegetarianFood", label: "vegetarian veggie food", Component: VegetarianFoodIcon },

  { name: "Tree01", label: "tree nature forest", Component: Tree01Icon },
  { name: "Leaf01", label: "leaf nature plant", Component: Leaf01Icon },
  { name: "Flower", label: "flower nature", Component: FlowerIcon },
  { name: "Mountain", label: "mountain nature peak", Component: MountainIcon },

  { name: "Sun01", label: "sun day weather", Component: Sun01Icon },
  { name: "Moon", label: "moon night", Component: MoonIcon },
  { name: "Snow", label: "snow winter", Component: SnowIcon },
  { name: "Fire", label: "fire flame hot", Component: FireIcon },
  { name: "Droplet", label: "droplet water", Component: DropletIcon },
  { name: "Tornado01", label: "tornado weather storm", Component: Tornado01Icon },
  { name: "Earth", label: "earth globe world", Component: EarthIcon },
  { name: "Globe02", label: "globe world internet", Component: Globe02Icon },

  { name: "Truck", label: "truck transport delivery", Component: TruckIcon },
  { name: "Train01", label: "train transport", Component: Train01Icon },
  { name: "Taxi", label: "taxi cab transport", Component: TaxiIcon },
  { name: "Rocket01", label: "rocket launch space", Component: Rocket01Icon },
  { name: "Tractor", label: "tractor farm vehicle", Component: TractorIcon },
  { name: "TrafficLight", label: "traffic light signal", Component: TrafficLightIcon },
  { name: "HotAirBalloon", label: "hot air balloon flight", Component: HotAirBalloonIcon },

  { name: "User", label: "user person profile", Component: UserIcon },
  { name: "Kid", label: "kid child", Component: KidIcon },
  { name: "Game", label: "game gaming", Component: GameIcon },
  { name: "Volleyball", label: "volleyball sport", Component: VolleyballIcon },
  { name: "Yoga01", label: "yoga meditation", Component: Yoga01Icon },
  { name: "Strategy", label: "strategy plan", Component: StrategyIcon },
  { name: "Puzzle", label: "puzzle solve game", Component: PuzzleIcon },

  { name: "Favourite", label: "favourite favorite love heart", Component: FavouriteIcon },
  { name: "Smile", label: "smile happy emoji", Component: SmileIcon },
  { name: "Star", label: "star favorite", Component: StarIcon },
  { name: "Skull", label: "skull dark", Component: SkullIcon },
  { name: "Mask", label: "mask incognito anonymous", Component: MaskIcon },
  { name: "Shirt01", label: "shirt clothing", Component: Shirt01Icon },
  { name: "Mortarboard01", label: "graduation cap school", Component: Mortarboard01Icon },

  { name: "Clock01", label: "clock time", Component: Clock01Icon },
  { name: "Mail01", label: "mail email letter", Component: Mail01Icon },
  { name: "Inbox", label: "inbox mail incoming", Component: InboxIcon },
  { name: "Telephone", label: "telephone phone call", Component: TelephoneIcon },
  { name: "Megaphone01", label: "megaphone announcement", Component: Megaphone01Icon },
  { name: "Rss", label: "rss feed news", Component: RssIcon },

  { name: "Search01", label: "search find", Component: Search01Icon },
  { name: "Zoom", label: "zoom magnify", Component: ZoomIcon },
  { name: "Compass", label: "compass navigation direction", Component: CompassIcon },
  { name: "Target01", label: "target goal aim", Component: Target01Icon },
  { name: "AnchorPoint", label: "anchor pin", Component: AnchorPointIcon },

  { name: "Tools", label: "tools utility wrench", Component: ToolsIcon },
  { name: "Wrench01", label: "wrench fix tool", Component: Wrench01Icon },
  { name: "Scissor01", label: "scissors cut", Component: Scissor01Icon },
  { name: "PenTool01", label: "pen tool design", Component: PenTool01Icon },
  { name: "Pencil", label: "pencil edit write", Component: PencilIcon },
  { name: "PaintBoard", label: "paint board art", Component: PaintBoardIcon },
  { name: "PaintBrush01", label: "paint brush art", Component: PaintBrush01Icon },
  { name: "PaintBucket", label: "paint bucket fill", Component: PaintBucketIcon },

  { name: "Key01", label: "key access password", Component: Key01Icon },
  { name: "Shield01", label: "shield security protect", Component: Shield01Icon },

  { name: "Flag01", label: "flag mark", Component: Flag01Icon },
  { name: "Bug02", label: "bug debug issue", Component: Bug02Icon },
  { name: "Flash", label: "flash speed lightning", Component: FlashIcon },
  { name: "Zap", label: "zap lightning electric", Component: ZapIcon },
  { name: "Umbrella", label: "umbrella rain weather", Component: UmbrellaIcon },
  { name: "Lamp01", label: "lamp light idea", Component: Lamp01Icon },
  { name: "Mixer", label: "mixer audio", Component: MixerIcon },
  { name: "Move", label: "move resize", Component: MoveIcon },
  { name: "WorkflowSquare01", label: "workflow process", Component: WorkflowSquare01Icon },
  { name: "Link01", label: "link chain url", Component: Link01Icon },
  { name: "Download01", label: "download save", Component: Download01Icon },
  { name: "Add01", label: "add plus", Component: Add01Icon },
  { name: "Hexagon", label: "hexagon shape", Component: HexagonIcon },
  { name: "Octagon", label: "octagon shape", Component: OctagonIcon },
  { name: "Triangle01", label: "triangle shape", Component: Triangle01Icon },
  { name: "Circle", label: "circle shape", Component: CircleIcon },
  { name: "Oval", label: "oval shape", Component: OvalIcon },
  { name: "Gears", label: "gear settings cog", Component: GearsIcon },
];

const PICKER_REGISTRY = new Map<string, PickerIcon>(
  PICKER_ICONS.map((p) => [p.name, p]),
);

export function lookupPickerIcon(name: string | undefined | null): PickerIcon | null {
  if (!name) return null;
  return PICKER_REGISTRY.get(name) ?? null;
}
